service: betty-bot

package:
  exclude:
    - '*.env'
    - README.md

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: prod
  profile: default
  lambdaHashingVersion: 20201221

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(15 23 ? * SUN-THU *)
      # - httpApi: 'GET /handler'